import { TradeRow } from './trade-row.model';

export var tradeData: TradeRow[] = [
  {
    symbol: 'AAPL',
    ccy: 'USD',
    qty: 120,
    side: 'Buy',
    riskOk: true,
    notes: 'Strong Q4 earnings',
    rowIndex: 0,
  },
  {
    symbol: 'TSLA',
    ccy: 'USD',
    qty: 80,
    side: 'Sell',
    riskOk: false,
    notes: 'Volatile week',
    rowIndex: 1,
  },
  { symbol: 'AMZN', ccy: 'USD', qty: 60, side: 'Buy', riskOk: true, notes: '', rowIndex: 2 },
  {
    symbol: 'MSFT',
    ccy: 'USD',
    qty: 45,
    side: 'Sell',
    riskOk: true,
    notes: 'Tech rotation',
    rowIndex: 3,
  },
  {
    symbol: 'NVDA',
    ccy: 'USD',
    qty: 30,
    side: 'Buy',
    riskOk: false,
    notes: 'Chip shortage',
    rowIndex: 4,
  },
  { symbol: 'GOOG', ccy: 'USD', qty: 75, side: 'Buy', riskOk: true, notes: '', rowIndex: 5 },
  {
    symbol: 'META',
    ccy: 'USD',
    qty: 90,
    side: 'Sell',
    riskOk: true,
    notes: 'High valuation',
    rowIndex: 6,
  },
  {
    symbol: 'BABA',
    ccy: 'HKD',
    qty: 100,
    side: 'Buy',
    riskOk: false,
    notes: 'China reopening',
    rowIndex: 7,
  },
  {
    symbol: 'NFLX',
    ccy: 'USD',
    qty: 40,
    side: 'Buy',
    riskOk: true,
    notes: 'Subscriber growth',
    rowIndex: 8,
  },
  {
    symbol: 'DIS',
    ccy: 'USD',
    qty: 70,
    side: 'Sell',
    riskOk: false,
    notes: 'Earnings miss',
    rowIndex: 9,
  },
];
